### ISSUE TITLE
Add https://arxiv.org/abs/2311.05800

### ISSUE THREAD

**Issue by thakur-nandan** [Albert-Ma/awesome-pretrained-models-for-information-retrieval#6]
Hi, thank you for maintaining such a robust list of publications.

Can you add this recent work with multilingual synthetic query generation on Arxiv -
[Leveraging LLMs for Synthesizing Training Data Across Many Languages in Multilingual Dense Retrieval](https://arxiv.org/abs/2311.05800)

Thanks,
Nandan

**Comment by Albert-Ma** [comment]
I will add this paper to the list. BTW, next time you can open a PR to add other good papers.
